
development:
   cloud_name: <%= Rails.application.credentials.dig(:cloudinary, :CLOUD_NAME) %>
  api_key: <%= Rails.application.credentials.dig(:cloudinary, :API_KEY) %>
  api_secret: <%= Rails.application.credentials.dig(:cloudinary, :API_SECRETE) %>
  secure: <%= Rails.application.credentials.dig(:cloudinary, :SECURE) %>
production:
  cloud_name: <%= Rails.application.credentials.dig(:cloudinary, :CLOUD_NAME) %>
  api_key: <%= Rails.application.credentials.dig(:cloudinary, :API_KEY) %>
  api_secret: <%= Rails.application.credentials.dig(:cloudinary, :API_SECRETE) %>
  secure: <%= Rails.application.credentials.dig(:cloudinary, :SECURE) %>
test:
   cloud_name: <%= Rails.application.credentials.dig(:cloudinary, :CLOUD_NAME) %>
  api_key: <%= Rails.application.credentials.dig(:cloudinary, :API_KEY) %>
  api_secret: <%= Rails.application.credentials.dig(:cloudinary, :API_SECRETE) %>
  secure: <%= Rails.application.credentials.dig(:cloudinary, :SECURE) %>
